/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/. 
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.1.8-160
 *
 */
import { RequestFlowBuilder } from '@fluencelabs/fluence/dist/api.unstable';



export async function collectServiceInterfaces(client, peer, services) {
    let request;
    const promise = new Promise((resolve, reject) => {
        request = new RequestFlowBuilder()
            .disableInjections()
            .withRawScript(
                `
(xor
 (seq
  (seq
   (seq
    (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
    (call %init_peer_id% ("getDataSrv" "peer") [] peer)
   )
   (call %init_peer_id% ("getDataSrv" "services") [] services)
  )
  (fold services srv
   (par
    (seq
     (seq
      (seq
       (call -relay- ("op" "noop") [])
       (xor
        (call peer ("srv" "get_interface") [srv.$.id!] iface)
        (seq
         (call -relay- ("op" "noop") [])
         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
        )
       )
      )
      (call -relay- ("op" "noop") [])
     )
     (call %init_peer_id% ("event" "collectServiceInterface") [peer srv.$.id! iface])
    )
    (next srv)
   )
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
)

            `,
            )
            .configHandler((h) => {
                h.on('getDataSrv', '-relay-', () => {
                    return client.relayPeerId;
                });
                h.on('getDataSrv', 'peer', () => {return peer;});
h.on('getDataSrv', 'services', () => {return services;});
                
                h.onEvent('errorHandlingSrv', 'error', (args) => {
                    // assuming error is the single argument
                    const [err] = args;
                    reject(err);
                });
            })
            .handleScriptError(reject)
            .handleTimeout(() => {
                reject('Request timed out for collectServiceInterfaces');
            })
            .build();
    });
    await client.initiateFlow(request);
    return Promise.race([promise, Promise.resolve()]);
}
      


export async function askAllAndSend(client, peer) {
    let request;
    const promise = new Promise((resolve, reject) => {
        request = new RequestFlowBuilder()
            .disableInjections()
            .withRawScript(
                `
(xor
 (seq
  (seq
   (seq
    (seq
     (seq
      (seq
       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
       (call %init_peer_id% ("getDataSrv" "peer") [] peer)
      )
      (call -relay- ("op" "noop") [])
     )
     (xor
      (seq
       (seq
        (seq
         (call peer ("peer" "identify") [] ident)
         (call peer ("dist" "list_blueprints") [] blueprints)
        )
        (call peer ("dist" "list_modules") [] modules)
       )
       (call peer ("srv" "list") [] services)
      )
      (seq
       (call -relay- ("op" "noop") [])
       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
      )
     )
    )
    (call -relay- ("op" "noop") [])
   )
   (call %init_peer_id% ("event" "collectPeerInfo") [peer ident services blueprints modules])
  )
  (fold services srv
   (par
    (seq
     (seq
      (seq
       (call -relay- ("op" "noop") [])
       (xor
        (call peer ("srv" "get_interface") [srv.$.id!] iface)
        (seq
         (call -relay- ("op" "noop") [])
         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
        )
       )
      )
      (call -relay- ("op" "noop") [])
     )
     (call %init_peer_id% ("event" "collectServiceInterface") [peer srv.$.id! iface])
    )
    (next srv)
   )
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
)

            `,
            )
            .configHandler((h) => {
                h.on('getDataSrv', '-relay-', () => {
                    return client.relayPeerId;
                });
                h.on('getDataSrv', 'peer', () => {return peer;});
                
                h.onEvent('errorHandlingSrv', 'error', (args) => {
                    // assuming error is the single argument
                    const [err] = args;
                    reject(err);
                });
            })
            .handleScriptError(reject)
            .handleTimeout(() => {
                reject('Request timed out for askAllAndSend');
            })
            .build();
    });
    await client.initiateFlow(request);
    return Promise.race([promise, Promise.resolve()]);
}
      


export async function findAndAskNeighboursSchema(client, relayPeerId, clientId) {
    let request;
    const promise = new Promise((resolve, reject) => {
        request = new RequestFlowBuilder()
            .disableInjections()
            .withRawScript(
                `
(xor
 (seq
  (seq
   (seq
    (seq
     (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
     (call %init_peer_id% ("getDataSrv" "relayPeerId") [] relayPeerId)
    )
    (call %init_peer_id% ("getDataSrv" "clientId") [] clientId)
   )
   (call -relay- ("op" "noop") [])
  )
  (xor
   (seq
    (call relayPeerId ("kad" "neighborhood") [clientId false] neighbors)
    (fold neighbors n
     (par
      (xor
       (seq
        (call n ("kad" "neighborhood") [clientId false] neighbors2)
        (fold neighbors2 n2
         (par
          (seq
           (seq
            (xor
             (seq
              (seq
               (seq
                (call n2 ("peer" "identify") [] ident)
                (call n2 ("dist" "list_blueprints") [] blueprints)
               )
               (call n2 ("dist" "list_modules") [] modules)
              )
              (call n2 ("srv" "list") [] services)
             )
             (seq
              (seq
               (call -relay- ("op" "noop") [])
               (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
              )
              (call -relay- ("op" "noop") [])
             )
            )
            (call n ("event" "collectPeerInfo") [n2 ident services blueprints modules])
           )
           (fold services srv
            (par
             (seq
              (xor
               (call n2 ("srv" "get_interface") [srv.$.id!] iface)
               (seq
                (seq
                 (call -relay- ("op" "noop") [])
                 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                )
                (call -relay- ("op" "noop") [])
               )
              )
              (call n ("event" "collectServiceInterface") [n2 srv.$.id! iface])
             )
             (next srv)
            )
           )
          )
          (next n2)
         )
        )
       )
       (seq
        (call -relay- ("op" "noop") [])
        (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
       )
      )
      (next n)
     )
    )
   )
   (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 5])
)

            `,
            )
            .configHandler((h) => {
                h.on('getDataSrv', '-relay-', () => {
                    return client.relayPeerId;
                });
                h.on('getDataSrv', 'relayPeerId', () => {return relayPeerId;});
h.on('getDataSrv', 'clientId', () => {return clientId;});
                
                h.onEvent('errorHandlingSrv', 'error', (args) => {
                    // assuming error is the single argument
                    const [err] = args;
                    reject(err);
                });
            })
            .handleScriptError(reject)
            .handleTimeout(() => {
                reject('Request timed out for findAndAskNeighboursSchema');
            })
            .build();
    });
    await client.initiateFlow(request);
    return Promise.race([promise, Promise.resolve()]);
}
      


export async function getAll(client, relayPeerId, knownPeers) {
    let request;
    const promise = new Promise((resolve, reject) => {
        request = new RequestFlowBuilder()
            .disableInjections()
            .withRawScript(
                `
(xor
 (seq
  (seq
   (seq
    (seq
     (seq
      (seq
       (seq
        (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
        (call %init_peer_id% ("getDataSrv" "relayPeerId") [] relayPeerId)
       )
       (call %init_peer_id% ("getDataSrv" "knownPeers") [] knownPeers)
      )
      (call -relay- ("op" "noop") [])
     )
     (xor
      (seq
       (seq
        (seq
         (call relayPeerId ("peer" "identify") [] ident)
         (call relayPeerId ("dist" "list_blueprints") [] blueprints)
        )
        (call relayPeerId ("dist" "list_modules") [] modules)
       )
       (call relayPeerId ("srv" "list") [] services)
      )
      (seq
       (call -relay- ("op" "noop") [])
       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
      )
     )
    )
    (call -relay- ("op" "noop") [])
   )
   (call %init_peer_id% ("event" "collectPeerInfo") [relayPeerId ident services blueprints modules])
  )
  (fold services srv
   (par
    (seq
     (seq
      (seq
       (call -relay- ("op" "noop") [])
       (xor
        (call relayPeerId ("srv" "get_interface") [srv.$.id!] iface)
        (seq
         (call -relay- ("op" "noop") [])
         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
        )
       )
      )
      (call -relay- ("op" "noop") [])
     )
     (call %init_peer_id% ("event" "collectServiceInterface") [relayPeerId srv.$.id! iface])
    )
    (next srv)
   )
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
)

            `,
            )
            .configHandler((h) => {
                h.on('getDataSrv', '-relay-', () => {
                    return client.relayPeerId;
                });
                h.on('getDataSrv', 'relayPeerId', () => {return relayPeerId;});
h.on('getDataSrv', 'knownPeers', () => {return knownPeers;});
                
                h.onEvent('errorHandlingSrv', 'error', (args) => {
                    // assuming error is the single argument
                    const [err] = args;
                    reject(err);
                });
            })
            .handleScriptError(reject)
            .handleTimeout(() => {
                reject('Request timed out for getAll');
            })
            .build();
    });
    await client.initiateFlow(request);
    return Promise.race([promise, Promise.resolve()]);
}
      