name: Deploy dashboard@master to DigitalOcean
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH
          uses: appleboy/ssh-action@v0.1.4
          with:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            KEY: ${{ secrets.SSHKEY }}
            script: |
              docker pull fluencelabs/dashboard:latest
              docker rm -f dashboard
              docker run -d --name dashboard -p443:443 -p80:80 -v caddy_data:/data fluencelabs/dashboard:latest