name: deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dashboard@master to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.DASHBOARD_HOST }}
          USERNAME: ${{ secrets.DASHBOARD_USERNAME }}
          KEY: ${{ secrets.DASHBOARD_SSHKEY }}
          script: |
            docker pull fluencelabs/dashboard:${{github.run_id}}
            docker rm -f dashboard
            docker run -d --name dashboard -p443:443 -p80:80 -v caddy_data:/data fluencelabs/dashboard:${{github.run_id}}
